<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <!-- style for navbar -->
    <style>
        ul{
            list-style-type: none;
            margin: 0;
            padding: 0;
        }

        li{
            display: inline;
        }
    </style>
</head>
<body>
    <nav>
        <ul>
            <!-- printing navbar -->
            <li><a href="?page=current">Current | </a></li>
            <li><a href="?page=completed">Completed | </a></li>
            <li><a href="?page=upload">Upload</a></li>
        </ul>
    </nav>
    <hr>
</body>
</html>